### PR TITLE
Fix CI failures

### PR DESCRIPTION
**Pull request by alisdair**
Something is causing CI failures with the 1.11.13 build during `go mod download`. I've tried upgrading the CircleCI orb, and switching to an explicit `circleci/go` Docker image, and neither works.

This PR now also drops the 1.11.13 build and replaces it with a (current) 1.17.3. I can't see any reason why we're required to maintain compatibility with Go 1.11 indefinitely, so I believe this change is reasonable.

### CODE REVIEW

**Review by apparentlymart — APPROVED** [review]
Agreed... I don't remember why we had selected those versions in particular, and this new pair seems as reasonable as the one we had before.

**Comment by jbardin** [comment]
Do we want to keep the go1.13 in there as well? That has also been unsupported for over a year.

I think we may want to update these to the hash mirror as well: `docker.mirror.hashicorp.services/cimg/go:1.17`

**Comment by jbardin** [comment]
(also, pinning the minor release always gets the latest patch, which should be OK since this isn't pinned to a specific `.go-version` like other CLI tools)

**Comment by alisdair** [comment]
Fair points! Sorry I merged just before you hit send.

I made an attempt at those changes, but [hit a new mysterious failure](https://app.circleci.com/pipelines/github/hashicorp/terraform-config-inspect/51/workflows/c4f125cf-b103-4ee5-92e3-e973a0ef3b43/jobs/100). I'm stepping back from this for now to move onto something else, but if you feel like digging in I'd be happy to review.

**Pull request merged**
